using System.ComponentModel.DataAnnotations;
using ERPTraining.Core.Training.Entities;

namespace ERPTraining.Core.DTOs
{
    // Content Management DTOs

    public class ContentSearchParams
    {
        public string? SearchTerm { get; set; }
        public string? ContentType { get; set; }
        public int? ModuleId { get; set; }
        public int? SectionId { get; set; }
        public List<string>? Tags { get; set; }
        public ContentStatus? Status { get; set; }
        public DateTime? CreatedAfter { get; set; }
        public DateTime? CreatedBefore { get; set; }
        public string? CreatedBy { get; set; }
        public int Page { get; set; } = 1;
        public int PageSize { get; set; } = 20;
        public string? SortBy { get; set; } = "CreatedAt";
        public bool SortDescending { get; set; } = true;
    }

    public class CreateContentDto
    {
        [Required]
        public string Title { get; set; } = string.Empty;
        
        [Required]
        public string Description { get; set; } = string.Empty;
        
        public string Content { get; set; } = string.Empty;
        
        [Required]
        public ContentType Type { get; set; }
        
        [Required]
        public int ModuleId { get; set; }
        
        public int? SectionId { get; set; }
        public int? LessonId { get; set; }
        
        public List<string> Tags { get; set; } = new();
        public List<string> AccessRoles { get; set; } = new();
        public List<string> AccessUsers { get; set; } = new();
        
        public string? ScribeLink { get; set; }
        public string? VideoUrl { get; set; }
        
        // Removed Files property to avoid IFormFile dependency
        
        public ContentStatus InitialStatus { get; set; } = ContentStatus.Draft;
        
        public Dictionary<string, object>? Metadata { get; set; }
    }

    public class UpdateContentDto
    {
        public string? Title { get; set; }
        public string? Description { get; set; }
        public string? Content { get; set; }
        public ContentType? Type { get; set; }
        public int? ModuleId { get; set; }
        public int? SectionId { get; set; }
        public int? LessonId { get; set; }
        public List<string>? Tags { get; set; }
        public List<string>? AccessRoles { get; set; }
        public List<string>? AccessUsers { get; set; }
        public string? ScribeLink { get; set; }
        public string? VideoUrl { get; set; }
        public bool CreateNewVersion { get; set; } = false;
        public string? VersionNotes { get; set; }
        public Dictionary<string, object>? Metadata { get; set; }
    }

    public class UpdateContentStatusDto
    {
        [Required]
        public ContentStatus Status { get; set; }
        
        public string? Notes { get; set; }
    }

    public class ContentVersionDto
    {
        public int Id { get; set; }
        public int ContentId { get; set; }
        public int VersionNumber { get; set; }
        public string VersionNotes { get; set; } = string.Empty;
        public string CreatedBy { get; set; } = string.Empty;
        public DateTime CreatedAt { get; set; }
        public UploadedContent Content { get; set; } = null!;
    }

    public class BulkUploadDto
    {
        [Required]
        public string UploadFolder { get; set; } = string.Empty;
        
        [Required]
        public int ModuleId { get; set; }
        
        public int? SectionId { get; set; }
        public List<string> Tags { get; set; } = new();
        public List<string> AccessRoles { get; set; } = new();
        public ContentType DefaultContentType { get; set; } = ContentType.Document;
        public bool AutoGenerateDescriptions { get; set; } = true;
    }

    public class ExportContentDto
    {
        [Required]
        public ContentExportFormat Format { get; set; }
        
        public Dictionary<string, object>? Options { get; set; }
    }

    public class AdvancedSearchDto
    {
        public string SearchTerm { get; set; } = string.Empty;
        public bool UseAI { get; set; } = false;
        public List<SearchFilter> Filters { get; set; } = new();
        public int MaxResults { get; set; } = 50;
        public bool IncludeSimilar { get; set; } = true;
    }

    public class SearchFilter
    {
        public string Field { get; set; } = string.Empty;
        public string Operator { get; set; } = "equals";
        public object Value { get; set; } = null!;
    }

    // Learning Modules DTOs

    public class LearningModuleFilter
    {
        public string? Category { get; set; }
        public DifficultyLevel? Difficulty { get; set; }
        public int? EstimatedMinutes { get; set; }
        public bool? HasPrerequisites { get; set; }
        public bool? IsCompleted { get; set; }
        public bool? IsRecommended { get; set; }
        public string? SortBy { get; set; } = "Recommended";
    }

    public class LearningProgressDto
    {
        public int ModuleId { get; set; }
        public int? SectionId { get; set; }
        public int? LessonId { get; set; }
        public double ProgressPercentage { get; set; }
        public TimeSpan TimeSpent { get; set; }
        public List<InteractionEvent> Interactions { get; set; } = new();
        public Dictionary<string, object>? AdditionalData { get; set; }
    }

    public class InteractionEvent
    {
        public string EventType { get; set; } = string.Empty;
        public DateTime Timestamp { get; set; }
        public Dictionary<string, object> Data { get; set; } = new();
    }

    public class AssessmentResponseDto
    {
        public int AssessmentId { get; set; }
        public List<QuestionResponse> Responses { get; set; } = new();
        public TimeSpan TimeSpent { get; set; }
    }

    public class QuestionResponse
    {
        public int QuestionId { get; set; }
        public List<string> SelectedAnswers { get; set; } = new();
        public string? FreeTextResponse { get; set; }
        public TimeSpan TimeSpent { get; set; }
    }

    public class AdaptivePathRequestDto
    {
        public List<int> TargetModuleIds { get; set; } = new();
        public List<string> LearningGoals { get; set; } = new();
        public DifficultyLevel PreferredDifficulty { get; set; }
        public int AvailableTimePerWeek { get; set; }
        public DateTime TargetCompletionDate { get; set; }
    }

    public class ModuleCompletionDto
    {
        public double FinalScore { get; set; }
        public TimeSpan TotalTimeSpent { get; set; }
        public List<string> CompletedSections { get; set; } = new();
        public string? Feedback { get; set; }
        public Dictionary<string, object>? CompletionData { get; set; }
    }

    public class LearningDashboardDto
    {
        public UserLearningStats Stats { get; set; } = new();
        public List<ModuleProgressSummary> CurrentModules { get; set; } = new();
        public List<Achievement> RecentAchievements { get; set; } = new();
        public List<LearningRecommendation> Recommendations { get; set; } = new();
        public LearningStreak Streak { get; set; } = new();
        public List<UpcomingDeadline> UpcomingDeadlines { get; set; } = new();
    }

    public class UserLearningStats
    {
        public int ModulesCompleted { get; set; }
        public int ModulesInProgress { get; set; }
        public TimeSpan TotalLearningTime { get; set; }
        public double AverageScore { get; set; }
        public int Rank { get; set; }
        public int TotalPoints { get; set; }
        public int BadgesEarned { get; set; }
    }

    public class ModuleProgressSummary
    {
        public int ModuleId { get; set; }
        public string Title { get; set; } = string.Empty;
        public double ProgressPercentage { get; set; }
        public DateTime LastAccessed { get; set; }
        public TimeSpan EstimatedTimeRemaining { get; set; }
        public bool IsOverdue { get; set; }
    }

    public class Achievement
    {
        public int Id { get; set; }
        public string Name { get; set; } = string.Empty;
        public string Description { get; set; } = string.Empty;
        public string IconUrl { get; set; } = string.Empty;
        public DateTime EarnedAt { get; set; }
        public int Points { get; set; }
        public AchievementType Type { get; set; }
    }

    public class LearningRecommendation
    {
        public int ModuleId { get; set; }
        public string Title { get; set; } = string.Empty;
        public string Reason { get; set; } = string.Empty;
        public double RelevanceScore { get; set; }
        public RecommendationType Type { get; set; }
    }

    public class LearningStreak
    {
        public int CurrentStreak { get; set; }
        public int LongestStreak { get; set; }
        public DateTime LastLearningDate { get; set; }
        public int DaysUntilBreak { get; set; }
    }

    public class UpcomingDeadline
    {
        public int ModuleId { get; set; }
        public string Title { get; set; } = string.Empty;
        public DateTime DueDate { get; set; }
        public int DaysRemaining { get; set; }
        public bool IsOverdue { get; set; }
    }

    // Enums

    public enum ContentStatus
    {
        Draft,
        InReview,
        Published,
        Archived,
        Deprecated
    }

    public enum ContentType
    {
        Document,
        Video,
        Interactive,
        Image,
        Audio,
        Simulation,
        Assessment
    }

    public enum ContentExportFormat
    {
        PDF,
        SCORM,
        xAPI,
        HTML,
        EPUB,
        Word
    }

    public enum DifficultyLevel
    {
        Beginner = 1,
        Intermediate = 2,
        Advanced = 3,
        Expert = 4
    }

    public enum AchievementType
    {
        ModuleCompletion,
        StreakMilestone,
        ScoreAchievement,
        TimeBasedMilestone,
        SocialEngagement,
        SkillMastery
    }

    public enum RecommendationType
    {
        NextInSequence,
        BasedOnInterests,
        PopularAmongPeers,
        SkillGapFiller,
        TrendingContent
    }

    // Additional DTOs for Content Management Service

    public class ContentSearchResultDto
    {
        public List<ContentDetailDto> Contents { get; set; } = new();
        public int TotalCount { get; set; }
        public int PageSize { get; set; }
        public int CurrentPage { get; set; }
        public int TotalPages { get; set; }
        public Dictionary<string, int> TypeCounts { get; set; } = new();
        public Dictionary<string, int> StatusCounts { get; set; } = new();
    }

    public class ContentDetailDto
    {
        public int Id { get; set; }
        public string Title { get; set; } = string.Empty;
        public string Description { get; set; } = string.Empty;
        public string Content { get; set; } = string.Empty;
        public ContentType Type { get; set; }
        public ContentStatus Status { get; set; }
        public int ModuleId { get; set; }
        public string ModuleName { get; set; } = string.Empty;
        public int? SectionId { get; set; }
        public string? SectionName { get; set; }
        public List<string> Tags { get; set; } = new();
        public string CreatedBy { get; set; } = string.Empty;
        public DateTime CreatedAt { get; set; }
        public DateTime? UpdatedAt { get; set; }
        public int ViewCount { get; set; }
        public double AverageRating { get; set; }
        public int RatingCount { get; set; }
        public int DownloadCount { get; set; }
        public long? FileSize { get; set; }
        public string? FilePath { get; set; }
        public string? FileName { get; set; }
        public string? ContentType { get; set; }
        public List<string> AccessRoles { get; set; } = new();
        public List<string> AccessUsers { get; set; } = new();
        public Dictionary<string, object>? Metadata { get; set; }
        public int VersionNumber { get; set; }
        public bool IsBookmarked { get; set; }
        public TimeSpan? EstimatedDuration { get; set; }
        public string? ThumbnailUrl { get; set; }
        public bool HasTranscript { get; set; }
        public bool HasClosedCaptions { get; set; }
        public bool IsAccessible { get; set; }
    }

    public class ContentAnalyticsDto
    {
        public int ContentId { get; set; }
        public string ContentTitle { get; set; } = string.Empty;
        public int TotalViews { get; set; }
        public int UniqueViewers { get; set; }
        public TimeSpan AverageViewDuration { get; set; }
        public double CompletionRate { get; set; }
        public double AverageRating { get; set; }
        public int TotalRatings { get; set; }
        public int DownloadCount { get; set; }
        public int BookmarkCount { get; set; }
        public int ShareCount { get; set; }
        public Dictionary<string, int> ViewsByDevice { get; set; } = new();
        public Dictionary<string, int> ViewsByLocation { get; set; } = new();
        public Dictionary<DateTime, int> ViewsByDate { get; set; } = new();
        public List<ContentInteractionDto> TopInteractions { get; set; } = new();
        public double EngagementScore { get; set; }
        public TimeSpan TotalTimeSpent { get; set; }
        public List<ContentFeedbackDto> RecentFeedback { get; set; } = new();
    }

    public class ContentPopularityDto
    {
        public int ContentId { get; set; }
        public string Title { get; set; } = string.Empty;
        public ContentType Type { get; set; }
        public int ViewCount { get; set; }
        public double AverageRating { get; set; }
        public double PopularityScore { get; set; }
        public int TrendingRank { get; set; }
        public string ThumbnailUrl { get; set; } = string.Empty;
    }

    public class ContentEngagementDto
    {
        public int ContentId { get; set; }
        public string Title { get; set; } = string.Empty;
        public double EngagementRate { get; set; }
        public TimeSpan AverageSessionDuration { get; set; }
        public double CompletionRate { get; set; }
        public int InteractionCount { get; set; }
        public double UserSatisfactionScore { get; set; }
        public Dictionary<string, double> EngagementMetrics { get; set; } = new();
    }

    public class BulkOperationResultDto
    {
        public int TotalProcessed { get; set; }
        public int SuccessCount { get; set; }
        public int FailureCount { get; set; }
        public List<string> SuccessMessages { get; set; } = new();
        public List<string> ErrorMessages { get; set; } = new();
        public List<ContentDetailDto> CreatedContent { get; set; } = new();
        public TimeSpan ProcessingTime { get; set; }
    }

    public class ContentStatsDto
    {
        public int TotalContent { get; set; }
        public int PublishedContent { get; set; }
        public int DraftContent { get; set; }
        public int ArchivedContent { get; set; }
        public Dictionary<ContentType, int> ContentByType { get; set; } = new();
        public Dictionary<string, int> ContentByModule { get; set; } = new();
        public long TotalFileSize { get; set; }
        public int TotalViews { get; set; }
        public int TotalDownloads { get; set; }
        public double AverageRating { get; set; }
        public DateTime LastUpdated { get; set; }
    }

    public class ContentUsageDto
    {
        public int ContentId { get; set; }
        public string Title { get; set; } = string.Empty;
        public ContentType Type { get; set; }
        public int ViewCount { get; set; }
        public int DownloadCount { get; set; }
        public TimeSpan TotalTimeSpent { get; set; }
        public int UniqueUsers { get; set; }
        public double CompletionRate { get; set; }
        public DateTime FirstAccessed { get; set; }
        public DateTime LastAccessed { get; set; }
    }

    public class ContentInteractionDto
    {
        public string UserId { get; set; } = string.Empty;
        public string UserName { get; set; } = string.Empty;
        public string InteractionType { get; set; } = string.Empty;
        public DateTime InteractionTime { get; set; }
        public Dictionary<string, object>? InteractionData { get; set; }
    }

    public class ContentFeedbackDto
    {
        public int Id { get; set; }
        public int ContentId { get; set; }
        public string UserId { get; set; } = string.Empty;
        public string UserName { get; set; } = string.Empty;
        public int Rating { get; set; }
        public string? Comment { get; set; }
        public DateTime CreatedAt { get; set; }
        public bool IsVerified { get; set; }
    }
}
